# Generated by Django 4.2.30 on 2026-04-28 19:33

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioCrue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('DIRECTOR', 'Director'), ('RADIOOPERADOR', 'Radiooperador')], default='RADIOOPERADOR', max_length=15, verbose_name='Rol')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario CRUE',
                'verbose_name_plural': 'Usuarios CRUE',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Remision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(help_text='DD/MM/YYYY HH:MM', verbose_name='Fecha y hora de ingreso')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del paciente')),
                ('tipo_doc', models.CharField(choices=[('CC', 'CC'), ('TI', 'TI'), ('CE', 'CE'), ('RC', 'RC'), ('CN', 'CN'), ('OTRO', 'OTRO')], default='CC', max_length=5, verbose_name='Tipo de documento')),
                ('doc', models.CharField(max_length=20, verbose_name='Número de documento')),
                ('gest', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, verbose_name='Gestante')),
                ('sexo', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=1, verbose_name='Sexo')),
                ('edad', models.CharField(help_text='Ej: 25 AÑOS, 3 MESES, 10 DIAS', max_length=20, verbose_name='Edad')),
                ('diagnostico', models.TextField(blank=True, default='', verbose_name='Diagnóstico')),
                ('ta', models.CharField(blank=True, default='', help_text='Ej: 120/80 o NO REFIERE', max_length=20, verbose_name='Tensión Arterial')),
                ('fc', models.CharField(blank=True, default='', help_text='Valor numérico o NO REFIERE', max_length=20, verbose_name='Frecuencia Cardíaca')),
                ('fr', models.CharField(blank=True, default='', help_text='Valor numérico o NO REFIERE', max_length=20, verbose_name='Frecuencia Respiratoria')),
                ('tm', models.CharField(blank=True, default='', help_text='Ej: 36° o NO REFIERE', max_length=10, verbose_name='Temperatura')),
                ('spo2', models.CharField(blank=True, default='', help_text='Ej: 98% o NO REFIERE', max_length=10, verbose_name='Saturación O2')),
                ('glasg', models.CharField(blank=True, default='15/15', help_text='Ej: 15/15 o NO REFIERE', max_length=10, verbose_name='Glasgow')),
                ('eps', models.CharField(blank=True, default='', max_length=100, verbose_name='EPS')),
                ('institucion_reporta', models.CharField(blank=True, default='', max_length=100, verbose_name='Institución que reporta')),
                ('municipio', models.CharField(blank=True, default='', max_length=100, verbose_name='Municipio')),
                ('medico_refiere', models.CharField(blank=True, default='', max_length=100, verbose_name='Médico que refiere')),
                ('medico_hudn', models.TextField(blank=True, default='', verbose_name='Médico HUDN que confirma')),
                ('radio_operador', models.CharField(blank=True, default='', max_length=100, verbose_name='Radio operador')),
                ('observacion', models.TextField(blank=True, default='', verbose_name='Observación')),
                ('aceptado', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('URG VITAL', 'URG VITAL')], default='NO', max_length=10, verbose_name='Aceptado')),
                ('fecha_res', models.DateTimeField(blank=True, help_text='DD/MM/YYYY HH:MM', null=True, verbose_name='Fecha y hora de respuesta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remisiones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Remisión',
                'verbose_name_plural': 'Remisiones',
                'ordering': ['fecha'],
                'indexes': [models.Index(fields=['fecha'], name='remisiones__fecha_d03769_idx'), models.Index(fields=['doc'], name='remisiones__doc_f8d1d1_idx')],
            },
        ),
    ]
