# Generated by Django 4.2.30 on 2026-05-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remisiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remision',
            name='doc',
            field=models.CharField(max_length=50, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='remision',
            name='fecha',
            field=models.DateTimeField(blank=True, help_text='DD/MM/YYYY HH:MM', null=True, verbose_name='Fecha y hora de ingreso'),
        ),
        migrations.AlterField(
            model_name='remision',
            name='institucion_reporta',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Institución que reporta'),
        ),
        migrations.AlterField(
            model_name='remision',
            name='medico_refiere',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Médico que refiere'),
        ),
        migrations.AlterField(
            model_name='remision',
            name='municipio',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='remision',
            name='spo2',
            field=models.CharField(blank=True, default='', help_text='Ej: 98% o NO REFIERE', max_length=20, verbose_name='Saturación O2'),
        ),
    ]
