# Generated by Django 4.2.30 on 2026-04-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remisiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('CIRUGIA DE COLUMNA', 'Cirugía de Columna'), ('CIRUGIA GENERAL', 'Cirugía General'), ('CIRUGIA PLASTICA', 'Cirugía Plástica'), ('CIRUGIA DEL TORAX', 'Cirugía del Tórax'), ('CIRUGIA MAXILOFACIAL', 'Cirugía Maxilofacial'), ('CIRUGIA VASCULAR', 'Cirugía Vascular'), ('DERMATOLOGIA', 'Dermatología'), ('ENDOCRINOLOGIA', 'Endocrinología'), ('EPILEPTOLOGIA', 'Epileptología'), ('GENETICA HUMANA', 'Genética Humana'), ('GINECOLOGIA', 'Ginecología'), ('HEMATOLOGIA', 'Hematología'), ('INFECTOLOGIA', 'Infectología'), ('MEDICINA INTERNA', 'Medicina Interna'), ('NEFROLOGIA', 'Nefrología'), ('NEFROLOGIA PEDIATRICA', 'Nefrología Pediátrica'), ('NEUROCIRUGIA', 'Neurocirugía'), ('NEUROLOGIA', 'Neurología'), ('NEUROLOGIA PEDIATRICA', 'Neurología Pediátrica'), ('NUTRICION CLINICA', 'Nutrición Clínica'), ('OCULOPLASTIA', 'Oculoplastia'), ('OFTALMOLOGIA', 'Oftalmología'), ('ORTOPEDIA', 'Ortopedia'), ('OTORRINOLARINGOLOGIA', 'Otorrinolaringología'), ('PEDIATRIA', 'Pediatría'), ('PERINATOLOGIA', 'Perinatología'), ('REUMATOLOGIA', 'Reumatología'), ('TOXICOLOGIA CLINICA', 'Toxicología Clínica'), ('OTRA', 'Otra')], default='', help_text='Especialidad requerida por el paciente', max_length=50, verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='remision',
            name='especialidad_otra',
            field=models.CharField(blank=True, default='', help_text='Especifique si seleccionó OTRA', max_length=100, verbose_name='Otra especialidad'),
        ),
    ]
