# Generated by Django 4.2.30 on 2026-05-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remisiones', '0002_alter_remision_doc_alter_remision_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocrue',
            name='rol',
            field=models.CharField(choices=[('RADIOOPERADOR', 'Radiooperador'), ('DIRECTOR', 'Director')], default='RADIOOPERADOR', max_length=15, verbose_name='Rol'),
        ),
    ]
