# Generated by Django 4.2.30 on 2026-04-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remisiones', '0002_remision_especialidad_remision_especialidad_otra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remision',
            name='especialidad',
            field=models.CharField(blank=True, default='', help_text='Especialidad requerida por el paciente', max_length=100, verbose_name='Especialidad'),
        ),
    ]
