# Generated by Django 4.2.30 on 2026-04-28 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remisiones', '0003_remove_especialidad_otra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remision',
            name='especialidad_otra',
        ),
    ]
