# Generated by Django 4.2.30 on 2026-05-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crue_remisiones', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='remision',
            index=models.Index(fields=['nombre'], name='crueremisio_nombre_89b773_idx'),
        ),
    ]
