# Generated by Django 4.2.30 on 2026-05-07 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Remision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, help_text='DD/MM/YYYY HH:MM', null=True, verbose_name='Fecha y hora de ingreso')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del paciente')),
                ('tipo_doc', models.CharField(choices=[('CC', 'CC'), ('TI', 'TI'), ('CE', 'CE'), ('RC', 'RC'), ('CN', 'CN'), ('OTRO', 'OTRO')], default='CC', max_length=5, verbose_name='Tipo de documento')),
                ('doc', models.CharField(max_length=50, verbose_name='Número de documento')),
                ('gest', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, verbose_name='Gestante')),
                ('sexo', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=1, verbose_name='Sexo')),
                ('edad', models.CharField(help_text='Ej: 25 AÑOS, 3 MESES, 10 DIAS', max_length=20, verbose_name='Edad')),
                ('especialidad', models.CharField(blank=True, default='', help_text='Especialidad requerida por el paciente', max_length=100, verbose_name='Especialidad')),
                ('diagnostico', models.TextField(blank=True, default='', verbose_name='Diagnóstico')),
                ('ta', models.CharField(blank=True, default='', help_text='Ej: 120/80 o NO REFIERE', max_length=20, verbose_name='Tensión Arterial')),
                ('fc', models.CharField(blank=True, default='', help_text='Valor numérico o NO REFIERE', max_length=20, verbose_name='Frecuencia Cardíaca')),
                ('fr', models.CharField(blank=True, default='', help_text='Valor numérico o NO REFIERE', max_length=20, verbose_name='Frecuencia Respiratoria')),
                ('tm', models.CharField(blank=True, default='', help_text='Ej: 36° o NO REFIERE', max_length=10, verbose_name='Temperatura')),
                ('spo2', models.CharField(blank=True, default='', help_text='Ej: 98% o NO REFIERE', max_length=20, verbose_name='Saturación O2')),
                ('glasg', models.CharField(blank=True, default='15/15', help_text='Ej: 15/15 o NO REFIERE', max_length=10, verbose_name='Glasgow')),
                ('eps', models.CharField(blank=True, default='', max_length=100, verbose_name='EPS')),
                ('institucion_reporta', models.CharField(blank=True, default='', max_length=200, verbose_name='Institución que reporta')),
                ('municipio', models.CharField(blank=True, default='', max_length=200, verbose_name='Municipio')),
                ('medico_refiere', models.CharField(blank=True, default='', max_length=200, verbose_name='Médico que refiere')),
                ('medico_hudn', models.CharField(blank=True, default='', max_length=300, verbose_name='Médico HUDN que confirma')),
                ('radio_operador', models.CharField(blank=True, default='', max_length=100, verbose_name='Radio operador')),
                ('observacion', models.TextField(blank=True, default='', verbose_name='Observación')),
                ('aceptado', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('URG VITAL', 'URG VITAL')], default='NO', max_length=10, verbose_name='Aceptado')),
                ('fecha_res', models.DateTimeField(blank=True, help_text='DD/MM/YYYY HH:MM', null=True, verbose_name='Fecha y hora de respuesta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remisiones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Remisión',
                'verbose_name_plural': 'Remisiones',
                'ordering': ['fecha'],
                'indexes': [models.Index(fields=['fecha'], name='crueremisio_fecha_a0112e_idx'), models.Index(fields=['doc'], name='crueremisio_doc_f4fbf5_idx')],
            },
        ),
    ]
